services:
  beecouple_nginx:
    image: nginx:stable-alpine
    container_name: beecouple_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - beecouple_backend
      - beecouple_minio
    networks:
      - beecouple-network

#  beecouple_frontend:

  beecouple_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: beecouple_backend
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend.env
    command: npm run start:dev
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - beecouple_postgresql-master
      - beecouple_postgresql-slave
      - beecouple_minio
      - beecouple_redis
    networks:
      - beecouple-network

  beecouple_postgresql-master:
    container_name: beecouple_postgresql-master
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=beecouple_password  # Set a strong password
      - POSTGRES_USER=beecouple_user
      - POSTGRES_DB=beecouple_db
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_DATABASE=beecouple_postgres
    networks:
      - beecouple-network

  beecouple_postgresql-slave:
    container_name: beecouple_postgresql-slave
    image: postgres:latest
    restart: always
    depends_on:
      - beecouple_postgresql-master
    environment:
      - POSTGRES_PASSWORD=beecouple_password  # Same as master
      - POSTGRES_USER=beecouple_user
      - POSTGRES_DB=beecouple_db
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
    networks:
      - beecouple-network

  #  beecouple_postgres:
  #    container_name: beecouple_postgres
  #    image: postgres:latest
  #    restart: always
  #    env_file:
  #      - docker.env
  #    ports:
  #      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  beecouple_redis:
    container_name: beecouple_redis
    image: "redis:alpine"
    env_file:
      - ./backend/docker.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - beecouple-network

  beecouple_minio:
    image: docker.io/bitnami/minio:2022
    container_name: beecouple_minio
    env_file:
      - ./backend/docker.env
    ports:
      - '9000:9000'
      - '9001:9001'
    platform: linux/amd64
    networks:
      - beecouple-network

#  beecouple_minio:
#    image: quay.io/minio/minio:RELEASE.2024-11-07T00-52-20Z
#    command: server --address ":9000" --console-address ":9001" /data
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    env_file:
#      - docker.env
#    #    environment:
#    #      MINIO_ROOT_USER: oncomed
#    #      MINIO_ROOT_PASSWORD: password
#    #      MINIO_DOMAIN: minio.ondose.com
#    #      MINIO_SERVER_URL: http://minio.ondose.com:9000
#    #      MINIO_BROWSER_REDIRECT_URL: http://minio.ondose.com:9001
#    volumes:
#      - ./minio_storage:/data
#    networks:
#      - beecouple-network

networks:
  beecouple-network:
    driver: bridge
